### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'float'.

### ISSUE THREAD

**Issue by RobinKoetsier** [ML-KULeuven/socceraction#557]
When wanting to convert an Opta dataframe to SPADL, I get the an error when using 
```
import socceraction.spadl.opta
```

the error is:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.8/site-packages/socceraction/spadl/__init__.py", line 16, in <module>
    from . import config, opta, statsbomb, wyscout
  File "/opt/anaconda3/lib/python3.8/site-packages/socceraction/spadl/opta.py", line 5, in <module>
    from pandera.typing import DataFrame
  File "/opt/anaconda3/lib/python3.8/site-packages/pandera/__init__.py", line 50, in <module>
    from . import errors, pandas_accessor, typing
  File "/opt/anaconda3/lib/python3.8/site-packages/pandera/typing/__init__.py", line 9, in <module>
    from . import dask, fastapi, geopandas, modin, pyspark
  File "/opt/anaconda3/lib/python3.8/site-packages/pandera/typing/dask.py", line 9, in <module>
    import dask.dataframe as dd
  File "/opt/anaconda3/lib/python3.8/site-packages/dask/dataframe/__init__.py", line 2, in <module>
    from .core import (
  File "/opt/anaconda3/lib/python3.8/site-packages/dask/dataframe/core.py", line 25, in <module>
    from .. import array as da
  File "/opt/anaconda3/lib/python3.8/site-packages/dask/array/__init__.py", line 3, in <module>
    from .core import (
  File "/opt/anaconda3/lib/python3.8/site-packages/dask/array/core.py", line 22, in <module>
    from . import chunk
  File "/opt/anaconda3/lib/python3.8/site-packages/dask/array/chunk.py", line 7, in <module>
    from . import numpy_compat as npcompat
  File "/opt/anaconda3/lib/python3.8/site-packages/dask/array/numpy_compat.py", line 21, in <module>
    np.divide(0.4, 1, casting="unsafe", dtype=np.float),
  File "/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

This was after reinstalling socceraction as I had problems with the convert_to_actions function (old version with different opta.py file I think).
Downgrading numpy doesn't work as that runs into dependancy errors.

**Comment by probberechts** [comment]
It looks like a conflict between some indirect dependencies of socceraction. Which versions of pandera, dask and numpy do you currently have installed?

**Comment by RobinKoetsier** [comment]
The version are:
```
dask      2.20.0
numpy   1.24.4
pandera 0.13.4

```
